import { TraceabilityItem, ControlCheckItem, InstrumentItem } from './types';

// ==========================================
// TKR1 0101-5000 (ORIGINAL)
// ==========================================
export const INITIAL_TRACEABILITY: TraceabilityItem[] = [
  { id: '1', code: '0101 0078', description: 'Sello', lot: '', serie: '', checked: false, observations: '' },
  { id: '2', code: 'O-90-2-125', description: 'O Ring (X8)', lot: '', serie: '', checked: false, observations: '' },
  { id: '3', code: 'O-90-2-231', description: 'O Ring (X1)', lot: '', serie: '', checked: false, observations: '' },
  { id: '4', code: 'O-90-2-232', description: 'O Ring (X2)', lot: '', serie: '', checked: false, observations: '' },
  { id: '5', code: 'O-90-2-234', description: 'O Ring (X2)', lot: '', serie: '', checked: false, observations: '' },
  { id: '6', code: 'O-90-2-331', description: 'O Ring (X1)', lot: '', serie: '', checked: false, observations: '' },
  { id: '7', code: '0101', description: 'Goma', lot: '', serie: '', checked: false, observations: 'Dureza Registrada: ' },
  { id: '8', code: '0101', description: 'Goma', lot: '', serie: '', checked: false, observations: 'Dureza Registrada: ' },
  { id: '9', code: '0101', description: 'Goma', lot: '', serie: '', checked: false, observations: 'Dureza Registrada: ' },
  { id: '10', code: '0000 0000 6003', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
  { id: '11', code: '0000 0000 6003', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
  { id: '12', code: '0000 0000 6003', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
  { id: '13', code: '0000 0000 1007', description: 'Mordaza', lot: '', serie: '', checked: false, observations: '' },
  { id: '14', code: '0000 0000 1007', description: 'Mordaza', lot: '', serie: '', checked: false, observations: '' },
  { id: '15', code: '0000 0000 1007', description: 'Mordaza', lot: '', serie: '', checked: false, observations: '' },
  { id: '16', code: '0000 0000 8021', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
  { id: '17', code: '0000 0000 8021', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
  { id: '18', code: '0101 0011', description: 'Anillo retencion flejes', lot: '', serie: '', checked: false, observations: '' },
  { id: '19', code: '0101 0019', description: 'Anillo Calibrador Superior', lot: '', serie: '', checked: false, observations: '' },
  { id: '20', code: '0101 5000 0001', description: 'Cabezal Superior 2 7/8 EUE Box', lot: '', serie: '', checked: false, observations: '' },
  { id: '21', code: '0101 5000 0005', description: 'Mandril', lot: '', serie: '', checked: false, observations: '' },
  { id: '22', code: '0101 5000 0010', description: 'Porta Piston', lot: '', serie: '', checked: false, observations: '' },
  { id: '23', code: '0101 5000 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
  { id: '24', code: '0101 5000 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
  { id: '25', code: '0101 5000 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
  { id: '26', code: '0101 5000 0021', description: 'Camisa Porta Gomas', lot: '', serie: '', checked: false, observations: '' },
  { id: '27', code: '0101 5000 0025', description: 'Cono Portamordazas', lot: '', serie: '', checked: false, observations: '' },
  { id: '28', code: '0101 5000 0030', description: 'Camisa Jota', lot: '', serie: '', checked: false, observations: '' },
  { id: '29', code: '0101 5000 0035', description: 'Pin De Jota', lot: '', serie: '', checked: false, observations: '' },
  { id: '30', code: '0000 0000 2007', description: 'Resorte (X16)', lot: '', serie: '', checked: false, observations: '' },
  { id: '31', code: '0000 0000 5007', description: 'Tornillo (X4)', lot: '', serie: '', checked: false, observations: '' },
];

export const INITIAL_CHECKS: ControlCheckItem[] = [
  { id: 1, description: 'Verificar visualmente estado de mordazas y conos portamordazas', isYesNo: true, hasMeasurement: false },
  { id: 2, description: 'Verificar visualmente estado de roscas (Foto 1)', isYesNo: true, hasMeasurement: false },
  { id: 3, description: 'Verificar estado de pistones y alojamientos con Calibres P/NP', isYesNo: true, hasMeasurement: false },
  { id: 4, description: 'Verificar cantidad y estado de O rings. (Foto 2)', isYesNo: true, hasMeasurement: false },
  { id: 5, description: 'Verificar estado de las secciones pulidas donde trabajan los O rings', isYesNo: true, hasMeasurement: false },
  { id: 6, description: 'Realizar prueba hidráulica y adjuntar registro', isYesNo: true, hasMeasurement: false },
  { 
    id: 7, 
    description: 'Inspeccionar y realizar control dimensional al Mandril.',
    isYesNo: false, 
    hasMeasurement: true,
    nominalValue: 399,
    acceptableValue: 400,
    nominalUnit: 'mm'
  },
  { 
    id: 8, 
    description: 'Verificar y realizar control dimensional al Camisa Porta Balanceadora (Detalle A)',
    isYesNo: false, 
    hasMeasurement: true,
    nominalValue: 153.5,
    acceptableValue: 152.5,
    nominalUnit: 'mm'
  },
  { 
    id: 9, 
    description: 'Verificar y realizar control dimensional al Camisa Porta Balanceadora (Detalle B)',
    isYesNo: false, 
    hasMeasurement: true,
    nominalValue: 4.0,
    acceptableValue: 3.8,
    nominalUnit: 'mm'
  },
  { 
    id: 10, 
    description: 'Inspeccionar y realizar control dimensional a Camisa Balanceadora Superior (0101-5000-0038)',
    isYesNo: false, 
    hasMeasurement: true,
    nominalValue: 128,
    acceptableValue: 127.5,
    nominalUnit: 'mm'
  },
  { 
    id: 11, 
    description: 'Inspeccionar y realizar control dimensional a Camisa Balanceadora Inferior (0101-5000-0008)',
    isYesNo: false, 
    hasMeasurement: true,
    nominalValue: 114,
    acceptableValue: 113.5,
    nominalUnit: 'mm'
  },
  { id: 12, description: 'Verificar correcto ensamble de Camisas Balanceadoras (Foto 3)', isYesNo: true, hasMeasurement: false },
  { id: 13, description: 'Inspeccionar estado de block de arrastre', isYesNo: true, hasMeasurement: false },
  { id: 14, description: 'Inspeccionar estado de porta block', isYesNo: true, hasMeasurement: false },
  { id: 15, description: 'Verificar torque a todas las uniones, tornillos y prisioneros', isYesNo: true, hasMeasurement: false },
];

// ==========================================
// TKR1 0178-5000 (NEW)
// ==========================================
export const INITIAL_TRACEABILITY_0178: TraceabilityItem[] = [
  { id: '1', code: '0101 0078', description: 'Sello', lot: '', serie: '', checked: false, observations: '' },
  { id: '2', code: 'O-90-2-125', description: 'O Ring (X8)', lot: '', serie: '', checked: false, observations: '' },
  { id: '3', code: 'O-90-2-231', description: 'O Ring (X1)', lot: '', serie: '', checked: false, observations: '' },
  { id: '4', code: 'O-90-2-234', description: 'O Ring (X2)', lot: '', serie: '', checked: false, observations: '' },
  { id: '5', code: 'O-90-2-235', description: 'O Ring (X2)', lot: '', serie: '', checked: false, observations: '' },
  { id: '6', code: 'O-90-2-331', description: 'O Ring (X1)', lot: '', serie: '', checked: false, observations: '' },
  { id: '7', code: '0101', description: 'Goma', lot: '', serie: '', checked: false, observations: 'Dureza Registrada: ' },
  { id: '8', code: '0101', description: 'Goma', lot: '', serie: '', checked: false, observations: 'Dureza Registrada: ' },
  { id: '9', code: '0101', description: 'Goma', lot: '', serie: '', checked: false, observations: 'Dureza Registrada: ' },
  { id: '10', code: '0000 0000 6003', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
  { id: '11', code: '0000 0000 6003', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
  { id: '12', code: '0000 0000 6003', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
  { id: '13', code: '0000 0000 6003', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
  { id: '14', code: '0000 0000 6003', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
  { id: '15', code: '0000 0000 6003', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
  { id: '16', code: '0000 0000 1007', description: '* Mordaza', lot: '', serie: '', checked: false, observations: '' },
  { id: '17', code: '0000 0000 1007', description: '* Mordaza', lot: '', serie: '', checked: false, observations: '' },
  { id: '18', code: '0000 0000 1007', description: '* Mordaza', lot: '', serie: '', checked: false, observations: '' },
  { id: '19', code: '0000 0000 8021', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
  { id: '20', code: '0000 0000 8021', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
  { id: '21', code: '0000 0000 8021', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
  { id: '22', code: '0178 0011', description: 'Anillo retencion flejes', lot: '', serie: '', checked: false, observations: '' },
  { id: '23', code: '0101 0019', description: 'Anillo Calibrador Superior', lot: '', serie: '', checked: false, observations: '' },
  { id: '24', code: '0101 0017', description: 'Anillos Separadores', lot: '', serie: '', checked: false, observations: '' },
  { id: '25', code: '0101 0017', description: 'Anillos Separadores', lot: '', serie: '', checked: false, observations: '' },
  { id: '26', code: '0101 0023', description: 'Anillo Calibrador Inferior', lot: '', serie: '', checked: false, observations: '' },
  { id: '27', code: '0178 5000 0001', description: '* Cabezal Superior 2 7/8 TSH PH-6 Box', lot: '', serie: '', checked: false, observations: '' },
  { id: '28', code: '0101 5000 0003', description: 'Tuerca Porta Sello', lot: '', serie: '', checked: false, observations: '' },
  { id: '29', code: '0178 5000 0005', description: '* Mandril', lot: '', serie: '', checked: false, observations: '' },
  { id: '30', code: '0178 5000 0007', description: 'Camisa Porta Balanceadora Superior', lot: '', serie: '', checked: false, observations: '' },
  { id: '31', code: '0178 5000 0008', description: 'Camisa Balanceadora Inferior', lot: '', serie: '', checked: false, observations: '' },
  { id: '32', code: '0178 5000 0010', description: 'Porta Piston', lot: '', serie: '', checked: false, observations: '' },
  { id: '33', code: '0101 5000 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
  { id: '34', code: '0101 5000 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
  { id: '35', code: '0101 5000 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
  { id: '36', code: '0101 5000 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
  { id: '37', code: '0101 5000 0021', description: '* Camisa Porta Gomas', lot: '', serie: '', checked: false, observations: '' },
  { id: '38', code: '0101 5000 0022', description: 'Anillo Retenedor Fleje', lot: '', serie: '', checked: false, observations: '' },
  { id: '39', code: '0101 5000 0025', description: 'Cono Portamordazas', lot: '', serie: '', checked: false, observations: '' },
  { id: '40', code: '0101 5000 0028', description: 'Anillo Porta Mordazas', lot: '', serie: '', checked: false, observations: '' },
  { id: '41', code: '0101 5000 0030', description: 'Camisa Jota', lot: '', serie: '', checked: false, observations: '' },
  { id: '42', code: '0101 5000 0032', description: 'Anillo Retencion Block', lot: '', serie: '', checked: false, observations: '' },
  { id: '43', code: '0101 5000 0035', description: '* Pin De Jota', lot: '', serie: '', checked: false, observations: '' },
  { id: '44', code: '0178 5000 0036', description: 'Camisa Porta Balanceadora Inferior', lot: '', serie: '', checked: false, observations: '' },
  { id: '45', code: '0178 5000 0038', description: 'Camisa Balanceadora Superior', lot: '', serie: '', checked: false, observations: '' },
  { id: '46', code: '0101 5000 0039', description: 'Camisaprotectora Jota', lot: '', serie: '', checked: false, observations: '' },
  { id: '47', code: '0000 0000 2007', description: 'Resorte (X16)', lot: '', serie: '', checked: false, observations: '' },
  { id: '48', code: '0000 0000 2011', description: 'Resorte (X8)', lot: '', serie: '', checked: false, observations: '' },
  { id: '49', code: '0000 0000 5007', description: 'Tornillo (X4)', lot: '', serie: '', checked: false, observations: '' },
  { id: '50', code: '0000 0000 5011', description: 'Tornillo (X2)', lot: '', serie: '', checked: false, observations: '' },
  { id: '51', code: '0000 0000 5038', description: 'Tornillo (X4)', lot: '', serie: '', checked: false, observations: '' },
];

export const INITIAL_CHECKS_0178: ControlCheckItem[] = [
  { id: 1, description: 'Verificar visualmente estado de mordazas y conos portamordazas', isYesNo: true, hasMeasurement: false },
  { id: 2, description: 'Verificar visualmente estado de roscas (Foto 1)', isYesNo: true, hasMeasurement: false },
  { id: 3, description: 'Verificar estado de pistones y alojamientos con Calibres P/NP', isYesNo: true, hasMeasurement: false },
  { id: 4, description: 'Verificar cantidad y estado de O rings. (Foto 2)', isYesNo: true, hasMeasurement: false },
  { id: 5, description: 'Verificar estado de las secciones pulidas donde trabajan los O rings', isYesNo: true, hasMeasurement: false },
  { id: 6, description: 'Realizar prueba hidráulica y adjuntar registro', isYesNo: true, hasMeasurement: false },
  { 
    id: 7, 
    description: 'Inspeccionar y realizar control dimensional al Mandril.',
    isYesNo: false, 
    hasMeasurement: true,
    nominalValue: 399, 
    acceptableValue: 401, 
    nominalUnit: 'mm'
  },
  { 
    id: 8, 
    description: 'Verificar y realizar control dimensional al Camisa Porta Balanceadora Superior. Detalle A:',
    isYesNo: false, 
    hasMeasurement: true,
    nominalValue: 154.9, 
    acceptableValue: 153.9, 
    nominalUnit: 'mm'
  },
  { 
    id: 9, 
    description: 'Detalle B:',
    isYesNo: false, 
    hasMeasurement: true,
    nominalValue: 4.0, 
    acceptableValue: 3.8, 
    nominalUnit: 'mm'
  },
  { 
    id: 10, 
    description: 'Detalle C:',
    isYesNo: false, 
    hasMeasurement: true,
    nominalValue: 1.8, 
    acceptableValue: 2.1, 
    nominalUnit: 'mm'
  },
  { 
    id: 11, 
    description: 'Inspeccionar y realizar control dimensional a Camisa Balanceadora Superior (0178-5000-0038).',
    isYesNo: false, 
    hasMeasurement: true,
    nominalValue: 128, 
    acceptableValue: 127, 
    nominalUnit: 'mm'
  },
  { 
    id: 12, 
    description: 'Inspeccionar y realizar control dimensional a Camisa Balanceadora Inferior (0178-5000-0008).',
    isYesNo: false, 
    hasMeasurement: true,
    nominalValue: 105.5, 
    acceptableValue: 104.5, 
    nominalUnit: 'mm'
  },
  { id: 13, description: 'Verificar correcto ensamble de Camisas Balanceadoras con  Camisas Porta Balanceadora (Foto 3)', isYesNo: true, hasMeasurement: false },
  { id: 14, description: 'Inspeccionar visualmente Tetones del Pin de Jota', isYesNo: true, hasMeasurement: false },
  { id: 15, description: 'Inspeccionar estado de block de arrastre', isYesNo: true, hasMeasurement: false },
  { id: 16, description: 'Inspeccionar estado de porta block', isYesNo: true, hasMeasurement: false },
  { id: 17, description: 'Verificar torque a todas las uniones, tornillos y prisioneros.', isYesNo: true, hasMeasurement: false },
];

// ==========================================
// TKR1 0101-5500 (NEW)
// ==========================================
export const INITIAL_TRACEABILITY_5500: TraceabilityItem[] = [
    { id: '1', code: '0101 0079', description: 'Sello', lot: '', serie: '', checked: false, observations: '' },
    { id: '2', code: 'O-90-2-224', description: 'O Ring (X8)', lot: '', serie: '', checked: false, observations: '' },
    { id: '3', code: 'O-90-2-332', description: 'O Ring (X1)', lot: '', serie: '', checked: false, observations: '' },
    { id: '4', code: 'O-90-2-336', description: 'O Ring (X1)', lot: '', serie: '', checked: false, observations: '' },
    { id: '5', code: 'O-90-2-337', description: 'O Ring (X1)', lot: '', serie: '', checked: false, observations: '' },
    { id: '6', code: 'O-90-2-340', description: 'O Ring (X1)', lot: '', serie: '', checked: false, observations: '' },
    { id: '7', code: '0101', description: 'Goma', lot: '', serie: '', checked: false, observations: 'Dureza Registrada: ' },
    { id: '8', code: '0101', description: 'Goma', lot: '', serie: '', checked: false, observations: 'Dureza Registrada: ' },
    { id: '9', code: '0101', description: 'Goma', lot: '', serie: '', checked: false, observations: 'Dureza Registrada: ' },
    { id: '10', code: '0101', description: 'Goma', lot: '', serie: '', checked: false, observations: 'Dureza Registrada: ' },
    { id: '11', code: '0000 0000', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
    { id: '12', code: '0000 0000', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
    { id: '13', code: '0000 0000', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
    { id: '14', code: '0000 0000', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
    { id: '15', code: '0000 0000', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
    { id: '16', code: '0000 0000', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
    { id: '17', code: '0000 0000 1005', description: '* Mordaza', lot: '', serie: '', checked: false, observations: '' },
    { id: '18', code: '0000 0000 1005', description: '* Mordaza', lot: '', serie: '', checked: false, observations: '' },
    { id: '19', code: '0000 0000 1005', description: '* Mordaza', lot: '', serie: '', checked: false, observations: '' },
    { id: '20', code: '0000 0000 1005', description: '* Mordaza', lot: '', serie: '', checked: false, observations: '' },
    { id: '21', code: '0000 0000 8002', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
    { id: '22', code: '0000 0000 8002', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
    { id: '23', code: '0000 0000 8002', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
    { id: '24', code: '0000 0000 8002', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
    { id: '25', code: '0101 0011', description: 'Anillo retencion flejes', lot: '', serie: '', checked: false, observations: '' },
    { id: '26', code: '0101 0019', description: 'Anillo Calibrador Superior', lot: '', serie: '', checked: false, observations: '' },
    { id: '27', code: '0101 0017', description: 'Anillos Separadores', lot: '', serie: '', checked: false, observations: '' },
    { id: '28', code: '0101 0017', description: 'Anillos Separadores', lot: '', serie: '', checked: false, observations: '' },
    { id: '29', code: '0101 0023', description: 'Anillo Calibrador Inferior', lot: '', serie: '', checked: false, observations: '' },
    { id: '30', code: '0101 5500 0001', description: '* Cabezal Superior 2 7/8" EUE Box', lot: '', serie: '', checked: false, observations: '' },
    { id: '31', code: '0101 5500 0003', description: 'Tuerca Porta Sello', lot: '', serie: '', checked: false, observations: '' },
    { id: '32', code: '0101 5500 0005', description: '* Mandril', lot: '', serie: '', checked: false, observations: '' },
    { id: '33', code: '0101 5500 0007', description: 'Camisa Porta Balanceadora', lot: '', serie: '', checked: false, observations: '' },
    { id: '34', code: '0101 5500 0008', description: 'Camisa Balanceadora', lot: '', serie: '', checked: false, observations: '' },
    { id: '35', code: '0101 5500 0010', description: 'Porta Piston', lot: '', serie: '', checked: false, observations: '' },
    { id: '36', code: '0101 5500 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
    { id: '37', code: '0101 5500 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
    { id: '38', code: '0101 5500 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
    { id: '39', code: '0101 5500 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
    { id: '40', code: '0101 5500 0021', description: '* Camisa Porta Gomas', lot: '', serie: '', checked: false, observations: '' },
    { id: '41', code: '0101 5500 0022', description: 'Anillo Retenedor Fleje', lot: '', serie: '', checked: false, observations: '' },
    { id: '42', code: '0101 5500 0024', description: 'Camisa Union', lot: '', serie: '', checked: false, observations: '' },
    { id: '43', code: '0101 5500 0025', description: 'Cono Portamordazas', lot: '', serie: '', checked: false, observations: '' },
    { id: '44', code: '0101 5500 0028', description: 'Anillo Porta Mordazas', lot: '', serie: '', checked: false, observations: '' },
    { id: '45', code: '0101 5500 0030', description: 'Camisa Jota', lot: '', serie: '', checked: false, observations: '' },
    { id: '46', code: '0101 5500 0032', description: 'Anillo Retención Block Superior', lot: '', serie: '', checked: false, observations: '' },
    { id: '47', code: '0101 5500 0035', description: '* Pin De Jota', lot: '', serie: '', checked: false, observations: '' },
    { id: '48', code: '0000 0000 2006', description: 'Resorte (X16)', lot: '', serie: '', checked: false, observations: '' },
    { id: '49', code: '0000 0000 2019', description: 'Resorte (X16)', lot: '', serie: '', checked: false, observations: '' },
    { id: '50', code: '0000 0000 5008', description: 'Tornillo (X4)', lot: '', serie: '', checked: false, observations: '' },
    { id: '51', code: '0000 0000 5011', description: 'Tornillo (X2)', lot: '', serie: '', checked: false, observations: '' },
    { id: '52', code: '0000 0000 5038', description: 'Tornillo (X4)', lot: '', serie: '', checked: false, observations: '' },
    { id: '53', code: '0000 0000 5039', description: 'Tornillo (X4)', lot: '', serie: '', checked: false, observations: '' },
    { id: '54', code: '0000 0000 5533', description: 'Tornillo (X2)', lot: '', serie: '', checked: false, observations: '' },
];

export const INITIAL_CHECKS_5500: ControlCheckItem[] = [
    { id: 1, description: 'Verificar visualmente estado de mordazas y conos portamordazas', isYesNo: true, hasMeasurement: false },
    { id: 2, description: 'Verificar visualmente estado de roscas (Foto 1)', isYesNo: true, hasMeasurement: false },
    { id: 3, description: 'Verificar estado de pistones y alojamientos con Calibres P/NP', isYesNo: true, hasMeasurement: false },
    { id: 4, description: 'Verificar cantidad y estado de O rings. (Foto 2)', isYesNo: true, hasMeasurement: false },
    { id: 5, description: 'Verificar estado de las secciones pulidas donde trabajan los O rings', isYesNo: true, hasMeasurement: false },
    { id: 6, description: 'Realizar prueba hidráulica y adjuntar registro', isYesNo: true, hasMeasurement: false },
    { 
      id: 7, 
      description: 'Inspeccionar y realizar control dimensional al Mandril.',
      isYesNo: false, 
      hasMeasurement: true,
      nominalValue: 272.5,
      acceptableValue: 274.5,
      nominalUnit: 'mm'
    },
    { 
      id: 8, 
      description: 'Verificar y realizar control dimensional al Camisa Porta Balanceadora. Detalle A:',
      isYesNo: false, 
      hasMeasurement: true,
      nominalValue: 195,
      acceptableValue: 191,
      nominalUnit: 'mm'
    },
    { 
      id: 9, 
      description: 'Detalle B:',
      isYesNo: false, 
      hasMeasurement: true,
      nominalValue: 4.3,
      acceptableValue: 4.1,
      nominalUnit: 'mm'
    },
    { 
      id: 10, 
      description: 'Detalle C:',
      isYesNo: false, 
      hasMeasurement: true,
      nominalValue: 1.7,
      acceptableValue: 2.0,
      nominalUnit: 'mm'
    },
    { 
      id: 11, 
      description: 'Inspeccionar y realizar control dimensional a Camisa Balanceadora.',
      isYesNo: false, 
      hasMeasurement: true,
      nominalValue: 90.5,
      acceptableValue: 89.5,
      nominalUnit: 'mm'
    },
    { id: 12, description: 'Inspeccionar visualmente Tetones del Pin de Jota', isYesNo: true, hasMeasurement: false },
    { id: 13, description: 'Inspeccionar estado de block de arrastre', isYesNo: true, hasMeasurement: false },
    { id: 14, description: 'Inspeccionar estado de porta block', isYesNo: true, hasMeasurement: false },
    { id: 15, description: 'Verificar torque a todas las uniones, tornillos y prisioneros.', isYesNo: true, hasMeasurement: false },
];

export const INITIAL_INSTRUMENTS: InstrumentItem[] = [
  { id: '1', name: 'Pie de Rey', code: 'CAL-DIG-300-C1', expiration: '', status: 'VENC' },
  { id: '2', name: 'Durometro', code: '', expiration: '', status: 'VENC' },
  { id: '3', name: 'Cinta Métrica', code: 'CINTA-MET-C1', expiration: '', status: 'VENC' },
  { id: '4', name: 'Manometro', code: '', expiration: '', status: 'VENC' },
  { id: '5', name: 'Conejo', code: 'CONEJO-177-C1', expiration: '', status: 'VENC' },
  { id: '6', name: 'P/NP Porta Pistón', code: '0101-5000-0051', expiration: '', status: 'VENC' },
  { id: '7', name: 'P/NP Pistón', code: '0101-5000-0052', expiration: '', status: 'VENC' },
  { id: '8', name: '', code: '', expiration: '', status: '' },
];

// ==========================================
// TKR1 0101-7000 (NEW)
// ==========================================
export const INITIAL_TRACEABILITY_7000: TraceabilityItem[] = [
    { id: '1', code: '0101 0092', description: 'Sello', lot: '', serie: '', checked: false, observations: '' },
    { id: '2', code: 'O-90-2-330', description: 'O Ring (X8)', lot: '', serie: '', checked: false, observations: '' },
    { id: '3', code: 'O-90-2-336', description: 'O Ring (X1)', lot: '', serie: '', checked: false, observations: '' },
    { id: '4', code: 'O-90-2-342', description: 'O Ring (X1)', lot: '', serie: '', checked: false, observations: '' },
    { id: '5', code: 'O-90-2-344', description: 'O Ring (X1)', lot: '', serie: '', checked: false, observations: '' },
    { id: '6', code: 'O-90-2-348', description: 'O Ring (X1)', lot: '', serie: '', checked: false, observations: '' },
    { id: '7', code: '0101', description: 'Goma', lot: '', serie: '', checked: false, observations: 'Dureza Registrada: ' },
    { id: '8', code: '0101', description: 'Goma', lot: '', serie: '', checked: false, observations: 'Dureza Registrada: ' },
    { id: '9', code: '0101', description: 'Goma', lot: '', serie: '', checked: false, observations: 'Dureza Registrada: ' },
    { id: '10', code: '0101', description: 'Goma', lot: '', serie: '', checked: false, observations: 'Dureza Registrada: ' },
    { id: '11', code: '0000 0000', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
    { id: '12', code: '0000 0000', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
    { id: '13', code: '0000 0000', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
    { id: '14', code: '0000 0000', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
    { id: '15', code: '0000 0000', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
    { id: '16', code: '0000 0000', description: 'Pistón', lot: '', serie: '', checked: false, observations: '' },
    { id: '17', code: '0000 0000', description: '* Mordaza', lot: '', serie: '', checked: false, observations: '' },
    { id: '18', code: '0000 0000', description: '* Mordaza', lot: '', serie: '', checked: false, observations: '' },
    { id: '19', code: '0000 0000', description: '* Mordaza', lot: '', serie: '', checked: false, observations: '' },
    { id: '20', code: '0000 0000', description: '* Mordaza', lot: '', serie: '', checked: false, observations: '' },
    { id: '21', code: '0000 0000', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
    { id: '22', code: '0000 0000', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
    { id: '23', code: '0000 0000', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
    { id: '24', code: '0000 0000', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
    { id: '25', code: '0000 0000', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
    { id: '26', code: '0000 0000', description: 'Blocks de Arrastre', lot: '', serie: '', checked: false, observations: '' },
    { id: '27', code: '0101 0011', description: 'Anillo retencion flejes', lot: '', serie: '', checked: false, observations: '' },
    { id: '28', code: '0101 0019', description: 'Anillo Calibrador Superior', lot: '', serie: '', checked: false, observations: '' },
    { id: '29', code: '0101 0017', description: 'Anillos Separadores', lot: '', serie: '', checked: false, observations: '' },
    { id: '30', code: '0101 0017', description: 'Anillos Separadores', lot: '', serie: '', checked: false, observations: '' },
    { id: '31', code: '0101 0023', description: 'Anillo Calibrador Inferior', lot: '', serie: '', checked: false, observations: '' },
    { id: '32', code: '0101 7000 0001', description: '* Cabezal Superior 2 7/8" EUE Box', lot: '', serie: '', checked: false, observations: '' },
    { id: '33', code: '0101 7000 0003', description: 'Tuerca Porta Sello', lot: '', serie: '', checked: false, observations: '' },
    { id: '34', code: '0101 7000 0005', description: '* Mandril', lot: '', serie: '', checked: false, observations: '' },
    { id: '35', code: '0101 7000 0007', description: 'Camisa Porta Balanceadora', lot: '', serie: '', checked: false, observations: '' },
    { id: '36', code: '0101 7000 0008', description: 'Camisa Balanceadora', lot: '', serie: '', checked: false, observations: '' },
    { id: '37', code: '0101 7000 0010', description: 'Porta Piston', lot: '', serie: '', checked: false, observations: '' },
    { id: '38', code: '0101 7000 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
    { id: '39', code: '0101 7000 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
    { id: '40', code: '0101 7000 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
    { id: '41', code: '0101 7000 0012', description: 'Fleje', lot: '', serie: '', checked: false, observations: '' },
    { id: '42', code: '0101 7000 0021', description: '* Camisa Porta Gomas', lot: '', serie: '', checked: false, observations: '' },
    { id: '43', code: '0101 7000 0022', description: 'Anillo Retenedor Fleje', lot: '', serie: '', checked: false, observations: '' },
    { id: '44', code: '0101 7000 0024', description: 'Camisa Union', lot: '', serie: '', checked: false, observations: '' },
    { id: '45', code: '0101 7000 0025', description: 'Cono Portamordazas', lot: '', serie: '', checked: false, observations: '' },
    { id: '46', code: '0101 7000 0028', description: 'Anillo Porta Mordazas', lot: '', serie: '', checked: false, observations: '' },
    { id: '47', code: '0101 7000 0030', description: 'Camisa Jota', lot: '', serie: '', checked: false, observations: '' },
    { id: '48', code: '0101 7000 0032', description: 'Anillo Retención Block Superior', lot: '', serie: '', checked: false, observations: '' },
    { id: '49', code: '0101 7000 0035', description: '* Pin De Jota', lot: '', serie: '', checked: false, observations: '' },
    { id: '50', code: '0000 0000 2008', description: 'Resorte (X24)', lot: '', serie: '', checked: false, observations: '' },
    { id: '51', code: '0000 0000 2011', description: 'Resorte (X24)', lot: '', serie: '', checked: false, observations: '' },
    { id: '52', code: '0000 0000 5008', description: 'Tornillo (X4)', lot: '', serie: '', checked: false, observations: '' },
    { id: '53', code: '0000 0000 5013', description: 'Tornillo (X2)', lot: '', serie: '', checked: false, observations: '' },
    { id: '54', code: '0000 0000 5037', description: 'Tornillo (X4)', lot: '', serie: '', checked: false, observations: '' },
    { id: '55', code: '0000 0000 5038', description: 'Tornillo (X8)', lot: '', serie: '', checked: false, observations: '' },
    { id: '56', code: '0000 0000 5533', description: 'Tornillo (X2)', lot: '', serie: '', checked: false, observations: '' },
];

export const INITIAL_CHECKS_7000: ControlCheckItem[] = [
    { id: 1, description: 'Verificar visualmente estado de mordazas y conos portamordazas', isYesNo: true, hasMeasurement: false },
    { id: 2, description: 'Verificar visualmente estado de roscas (Foto 1)', isYesNo: true, hasMeasurement: false },
    { id: 3, description: 'Verificar estado de pistones y alojamientos con Calibres P/NP', isYesNo: true, hasMeasurement: false },
    { id: 4, description: 'Verificar cantidad y estado de O rings. (Foto 2)', isYesNo: true, hasMeasurement: false },
    { id: 5, description: 'Verificar estado de las secciones pulidas donde trabajan los O rings', isYesNo: true, hasMeasurement: false },
    { id: 6, description: 'Realizar prueba hidráulica y adjuntar registro', isYesNo: true, hasMeasurement: false },
    { 
      id: 7, 
      description: 'Inspeccionar y realizar control dimensional al Mandril.',
      isYesNo: false, 
      hasMeasurement: true,
      nominalValue: 309,
      acceptableValue: 312,
      nominalUnit: 'mm'
    },
    { 
      id: 8, 
      description: 'Verificar y realizar control dimensional al Camisa Porta Balanceadora. Detalle A:',
      isYesNo: false, 
      hasMeasurement: true,
      nominalValue: 249,
      acceptableValue: 244,
      nominalUnit: 'mm'
    },
    { 
      id: 9, 
      description: 'Detalle B:',
      isYesNo: false, 
      hasMeasurement: true,
      nominalValue: 4.3,
      acceptableValue: 4.1,
      nominalUnit: 'mm'
    },
    { 
      id: 10, 
      description: 'Detalle C:',
      isYesNo: false, 
      hasMeasurement: true,
      nominalValue: 1.4,
      acceptableValue: 1.7,
      nominalUnit: 'mm'
    },
    { 
      id: 11, 
      description: 'Inspeccionar y realizar control dimensional a Camisa Balanceadora.',
      isYesNo: false, 
      hasMeasurement: true,
      nominalValue: 101,
      acceptableValue: 99.5,
      nominalUnit: 'mm'
    },
    { id: 12, description: 'Inspeccionar visualmente Tetones del Pin de Jota', isYesNo: true, hasMeasurement: false },
    { id: 13, description: 'Inspeccionar estado de block de arrastre', isYesNo: true, hasMeasurement: false },
    { id: 14, description: 'Inspeccionar estado de porta block', isYesNo: true, hasMeasurement: false },
    { id: 15, description: 'Verificar torque a todas las uniones, tornillos y prisioneros.', isYesNo: true, hasMeasurement: false },
];

export const INITIAL_INSTRUMENTS_7000: InstrumentItem[] = [
    { id: '1', name: 'Pie de Rey', code: 'CAL-DIG-300-C1', expiration: '', status: 'VENC' },
    { id: '2', name: 'Cinta Métrica', code: 'CINTA-MET-C1', expiration: '', status: 'VENC' },
    { id: '3', name: 'Conejo', code: 'CONEJO-244-C1', expiration: '', status: 'VENC' },
    { id: '4', name: 'P/NP Porta Pistón', code: '0101-7000-0051', expiration: '', status: 'VENC' },
    { id: '5', name: 'P/NP Pistón', code: '0101-7000-0052', expiration: '', status: 'VENC' },
    { id: '6', name: 'NP Portabalanceadora', code: '0101-7000-0053', expiration: '', status: 'VENC' },
    { id: '7', name: 'P Portabalanceadora', code: '0101-7000-0054', expiration: '', status: 'VENC' },
    { id: '8', name: 'Durometro', code: '', expiration: '', status: 'VENC' },
    { id: '9', name: 'Manometro', code: '', expiration: '', status: 'VENC' },
];